<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-7MH8S9EP" name="HRM_Employee.Employee_1_Add_Employee" tests="3" failures="1" timestamp="01 Dec 2021 09:04:34 GMT" time="22.354" errors="0">
  <testcase name="Employee_2_Upload_Avatar" time="0.002" classname="HRM_Employee.Employee_1_Add_Employee"/>
  <testcase name="Employee_3_Edit_Personal_Detail" time="0.002" classname="HRM_Employee.Employee_1_Add_Employee"/>
  <testcase name="Employee_1_Add_New_Employee" time="22.350" classname="HRM_Employee.Employee_1_Add_Employee">
    <failure type="java.lang.AssertionError" message="expected [KHOA1] but found [KHOA]">
      <![CDATA[java.lang.AssertionError: expected [KHOA1] but found [KHOA]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at Commons.BaseTest.checkEquals(BaseTest.java:132)
at Commons.BaseTest.verifyEquals(BaseTest.java:146)
at HRM_Employee.Employee_1_Add_Employee.Employee_1_Add_New_Employee(Employee_1_Add_Employee.java:97)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Employee_1_Add_New_Employee -->
</testsuite> <!-- HRM_Employee.Employee_1_Add_Employee -->
